"""Structural model variants for user-configured experiments."""

STRUCTURAL_VARIANTS = {
    "full": {
        "drcm_mode": "full",
        "output_mode": "full",
        "bem_mode": "full",
        "dcea_mode": "full",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.2,
        "match_loss_weight": 0.2,
        "domain_loss_weight": 1.0,
        "view_loss_weight": 1.0,
    },
    "without_drcm": {
        "drcm_mode": "off",
        "output_mode": "full",
        "bem_mode": "full",
        "dcea_mode": "full",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.2,
        "match_loss_weight": 0.2,
        "domain_loss_weight": 0.0,
        "view_loss_weight": 1.0,
    },
    "without_bem": {
        "drcm_mode": "full",
        "output_mode": "shared_evidence",
        "bem_mode": "full",
        "dcea_mode": "full",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.2,
        "match_loss_weight": 0.0,
        "domain_loss_weight": 1.0,
        "view_loss_weight": 1.0,
    },
    # Paper: w/o Refine; archived experiment name: dcea_reference_only.
    "without_refine": {
        "drcm_mode": "full",
        "output_mode": "reference_only",
        "bem_mode": "full",
        "dcea_mode": "off",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.0,
        "match_loss_weight": 0.2,
        "domain_loss_weight": 1.0,
        "view_loss_weight": 1.0,
    },
    "without_dcea": {
        "drcm_mode": "full",
        "output_mode": "fixed_mean",
        "bem_mode": "full",
        "dcea_mode": "off",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.0,
        "match_loss_weight": 0.2,
        "domain_loss_weight": 1.0,
        "view_loss_weight": 1.0,
    },
    "without_all": {
        "drcm_mode": "off",
        "output_mode": "plain_ffn_early",
        "bem_mode": "off",
        "dcea_mode": "off",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.0,
        "match_loss_weight": 0.0,
        "domain_loss_weight": 0.0,
        "view_loss_weight": 0.0,
    },
    # Legacy output-only baseline; not the paper's all-component removal.
    "without_both": {
        "drcm_mode": "full",
        "output_mode": "plain_ffn",
        "bem_mode": "off",
        "dcea_mode": "off",
        "state_mode": "dual",
        "arbitration_loss_weight": 0.0,
        "match_loss_weight": 0.0,
        "domain_loss_weight": 0.0,
        "view_loss_weight": 0.0,
    },
}
